name: Schneckenhaus
main: io.github.lama06.schneckenhaus.SchneckenPlugin
description: Makes it possible to enter shulker boxes and carry your house around with you like a snail.
version: 1.0.0
api-version: 1.20
website: https://github.com/Lama06/Schneckenhaus
author: Lama06
commands:
  schneckenhaus:
    usage: /schneckenhaus info [id] | /schneckenhaus create [size] [color]
    description: The main command of the Schneckenhaus plugin.
    aliases: sh