#    _____      _                     _              _
#   / ____|    | |                   | |            | |
#  | (___   ___| |__  _ __   ___  ___| | _____ _ __ | |__   __ _ _   _ ___
#   \___ \ / __| '_ \| '_ \ / _ \/ __| |/ / _ \ '_ \| '_ \ / _` | | | / __|
#   ____) | (__| | | | | | |  __/ (__|   <  __/ | | | | | | (_| | |_| \__ \
#  |_____/ \___|_| |_|_| |_|\___|\___|_|\_\___|_| |_|_| |_|\__,_|\__,_|___/

# Spigot page: https://www.spigotmc.org/resources/schneckenhaus.116315/
# Source code available on GitHub: https://github.com/Lama06/Schneckenhaus
# Contact the author (bugs, feature requests etc.): andreasprues36@gmail.com
# If you enjoy the plugin, consider making a donation on PayPal
# If you agree, your donation will be mentioned on the plugin's websites
# Edit the configuration while the server is turned off

# Allows players to enter a snail shell when already inside another one
nesting: true

# Prevents players from breaking other players' snail shells
theft_prevention: false

home_shell:
  # If enabled, every player will automatically receive a new snail shell on first spawn.
  enabled: false
  size: 16
  # Allow players to access their home shell using /schneckenhaus home or /sh home
  command: true
  # If a player respawns, he will be given his home snail shell, given that he has los it.
  prevent_homelessness: true

# Configuration for shulker snail shells
shulker:
  # Whether shulker snail shells can be crafted
  enabled: true
  # Ingredients required to craft a shulker snail shell
  ingredients:
    - spyglass
  # Can be used to increase the shulker snail shell's size
  size_ingredient: gold_ingot
  # The size that will be applied if no size ingredient is used
  initial_size: 4
  # Added to the initial size for every size ingredient used
  size_per_ingredient: 2
# Configuration for chest snail shells (see shulker config)
chest:
  enabled: true
  ingredients:
    - spyglass
  size_ingredient: diamond
  initial_size: 4
  size_per_ingredient: 1
# Configuration of custom snail shells
# Be aware that deleting a snail shell from this list will make all its instances invalid
custom: { }

# Don't change this! Doing so will cause data corruption.
data_version: placeholder