#    _____      _                     _              _
#   / ____|    | |                   | |            | |
#  | (___   ___| |__  _ __   ___  ___| | _____ _ __ | |__   __ _ _   _ ___
#   \___ \ / __| '_ \| '_ \ / _ \/ __| |/ / _ \ '_ \| '_ \ / _` | | | / __|
#   ____) | (__| | | | | | |  __/ (__|   <  __/ | | | | | | (_| | |_| \__ \
#  |_____/ \___|_| |_|_| |_|\___|\___|_|\_\___|_| |_|_| |_|\__,_|\__,_|___/

# Please report issues, give feedback or request features on GitHub: https://github.com/Lama06/Schneckenhaus

data_version: ${project.version}

nesting: true


shulker:
  enabled: true
  ingredients:
    - spyglass
  size_ingredient: gold_ingot
  initial_size: 4
  size_per_ingredient: 2
chest:
  enabled: true
  ingredients:
    - spyglass
  size_ingredient: diamond
  initial_size: 4
  size_per_ingredient: 1
custom: { }