#    _____      _                     _              _
#   / ____|    | |                   | |            | |
#  | (___   ___| |__  _ __   ___  ___| | _____ _ __ | |__   __ _ _   _ ___
#   \___ \ / __| '_ \| '_ \ / _ \/ __| |/ / _ \ '_ \| '_ \ / _` | | | / __|
#   ____) | (__| | | | | | |  __/ (__|   <  __/ | | | | | | (_| | |_| \__ \
#  |_____/ \___|_| |_|_| |_|\___|\___|_|\_\___|_| |_|_| |_|\__,_|\__,_|___/

# Please report issues, give feedback or request features on GitHub: https://github.com/Lama06/Schneckenhaus

# Allows players to enter a snail shell when already inside another one
nesting: true

# Configuration for shulker snail shells
shulker:
  # Whether shulker snail shells can be crafted
  enabled: true
  # Ingredients required to craft a shulker snail shell
  ingredients:
    - spyglass
  # Can be used to increase the shulker snail shell's size
  size_ingredient: gold_ingot
  # The size that will be applied if no size ingredient is used
  initial_size: 4
  # Added to the initial size for every size ingredient used
  size_per_ingredient: 2
# Configuration for chest snail shells (see shulker config)
chest:
  enabled: true
  ingredients:
    - spyglass
  size_ingredient: diamond
  initial_size: 4
  size_per_ingredient: 1
# Configuration of custom snail shells
# Be aware that deleting a snail shell from this list will make all its instances invalid
custom: { }

# Don't change this! Doing so will cause data corruption.
data_version: ${project.version}