name: Schneckenhaus
main: io.github.lama06.schneckenhaus.SchneckenPlugin
description: Makes it possible to enter shulker boxes and carry your house around with you like a snail.
version: 2.1.0
api-version: 1.20
website: https://github.com/Lama06/Schneckenhaus
author: Lama06
commands:
  schneckenhaus:
    description: The main command of the Schneckenhaus plugin.
    usage: /sh help
    aliases: sh
permissions:
  schneckenhaus.*:
    default: op
    description: Allows to use every feature of the Schneckenhaus plugin
    children:
      schneckenhaus.craft: true
      schneckenhaus.enter: true
      schneckenhaus.command: true
  schneckenhaus.craft:
    description: Allows to craft snail shells
    default: true
  schneckenhaus.enter:
    description: Allows to enter snail shells
    default: true
  schneckenhaus.command:
    description: Allows to use the /schneckenhaus command
    default: op