name: Schneckenhaus
main: io.github.lama06.schneckenhaus.SchneckenhausPlugin
description: Enter shulker boxes, chests, player heads and much more!
version: ${project.version}
api-version: 1.21
website: https://github.com/Lama06/Schneckenhaus
author: Lama06
loadbefore:
  - WorldEdit